CHAR_WIDTH = 34
CHAR_HEIGHT = 72

MAX_FPS = 1
FOV = 60
SHOW_FPS = False

RENDER_SCALE_COEFFICIENT = 1

height_ratio = (CHAR_HEIGHT / CHAR_WIDTH / 2) ** 0.5 / 2
render_coefficient_axis = RENDER_SCALE_COEFFICIENT ** 0.5
